/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tesstcalss;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class CatMananger extends javax.swing.JFrame {
    Cat cat;
    ArrayList<Cat> listCat;
    int index;
    DefaultTableModel model;
    /**
     * Creates new form CatMananger
     */
    public CatMananger() {
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        model  = (DefaultTableModel) tb_Catmanaget.getModel();
        cat = new Cat();
        listCat = new ArrayList<>();
        listCat.add(new Cat("Meo 1 ",2, "mate"));
        listCat.add(new Cat("Meo 2 ", 3, "female" ));
        listCat.add(new Cat("Meo 3 ", 5, "male"));
        listCat.add(new Cat("Meo 4 ", 2, "femae"));
        model.setRowCount(0);
        for(Cat cat:listCat){
            model.addRow(new Object[]{cat.getName(), cat.getAge(), cat.getgt()});
        }
        tb_Catmanaget.setRowSelectionInterval(0, 0);
        index = 0;
        showDetail();
    }
    public void clearFrom(){
        index = - 1;
        tf_name.setText("");
        tf_tuoi.setText("");
    }
    public void addCat(){
        if(checkFrom()){
            

        cat.setName(tf_name.getText());
        cat.setName(tf_tuoi.getText());
        if(rdo_Male.isSelected()){
            cat.setGt("male");
        }else {
            cat.setGt("Female");
        }
        listCat.add(cat);
        model.addRow(new Object[]{cat.getName(), String.valueOf(cat.getAge()),cat.getgt()});
        }
        
    }
    public boolean checkFrom(){
        if(tf_name.getText().length()==0 || tf_tuoi.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong cac o nhap");
            return false;
        }else if(Integer.parseInt(tf_tuoi.getText()) >5){
            JOptionPane.showMessageDialog(this, "Tuoi khong duoc lon hon 5");
            return false;
        }
        return true;
    }
    public void showDetail(){
        index = tb_Catmanaget.getSelectedRow();
        cat = listCat.get(index);
        tf_name.setText(cat.getName());
        tf_tuoi.setText(String.valueOf(cat.getAge()));
        if(cat.getgt().equalsIgnoreCase("female") ){
            rd0Female.setSelected(true);
        }else{
            rdo_Male.setSelected(true);
        }
        
        
    }
    public void prevFsist(){
        if(index >=0){
            tb_Catmanaget.setRowSelectionInterval(0, 0);
            index = listCat.size() -1;
        }else {
            System.out.println("Khong co phan tu");
        }
        
    }
    public void showRecord(){
        index = tb_Catmanaget.getSelectedRow();
        tf_recordNumber.setText((index+1) + " 0f " + listCat.size());
        index= listCat.size()-1;
        
    }
    public void prev(){
        if(index >= 0){
             index = tb_Catmanaget.getSelectedRow();
            index --;
            tb_Catmanaget.setRowSelectionInterval(index, index);
            
        }
    }
      public void next(){
        if(index <=listCat.size()-1){
            index = tb_Catmanaget.getSelectedRow();
            index++;
            tb_Catmanaget.setRowSelectionInterval(index, index);
            
        }
    }
      public void last(){
          if(index <= listCat.size()-1){
               index = tb_Catmanaget.getSelectedRow();
              tb_Catmanaget.setRowSelectionInterval(listCat.size()-1, listCat.size()-1);
              index =0;
          }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_tuoi = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        prevFrist = new javax.swing.JButton();
        prevrow = new javax.swing.JButton();
        next = new javax.swing.JButton();
        nextLast = new javax.swing.JButton();
        tf_recordNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Catmanaget = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rdo_Male = new javax.swing.JRadioButton();
        rd0Female = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CAT MANAGER");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        prevFrist.setText("|<");
        prevFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevFristActionPerformed(evt);
            }
        });

        prevrow.setText("<<");
        prevrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevrowActionPerformed(evt);
            }
        });

        next.setText(">>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        nextLast.setText(">|");
        nextLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLastActionPerformed(evt);
            }
        });

        tb_Catmanaget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Age", "Genger"
            }
        ));
        tb_Catmanaget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_CatmanagetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Catmanaget);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gender"));

        buttonGroup1.add(rdo_Male);
        rdo_Male.setText("Male");

        buttonGroup1.add(rd0Female);
        rd0Female.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo_Male)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(rd0Female)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Male)
                    .addComponent(rd0Female))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(prevFrist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prevrow)
                        .addGap(18, 18, 18)
                        .addComponent(tf_recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextLast))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(tf_tuoi)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_new)
                            .addComponent(btn_save))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_new))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(nextLast)
                    .addComponent(tf_recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevrow)
                    .addComponent(prevFrist))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        addCat();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void prevFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevFristActionPerformed
        // TODO add your handling code here:
        prevFsist();
    }//GEN-LAST:event_prevFristActionPerformed

    private void prevrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevrowActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_prevrowActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_nextActionPerformed

    private void nextLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_nextLastActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        clearFrom();
    }//GEN-LAST:event_btn_newActionPerformed

    private void tb_CatmanagetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CatmanagetMouseClicked
        // TODO add your handling code here:
        showDetail();
        showRecord();
    }//GEN-LAST:event_tb_CatmanagetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatMananger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatMananger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatMananger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatMananger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatMananger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton next;
    private javax.swing.JButton nextLast;
    private javax.swing.JButton prevFrist;
    private javax.swing.JButton prevrow;
    private javax.swing.JRadioButton rd0Female;
    private javax.swing.JRadioButton rdo_Male;
    private javax.swing.JTable tb_Catmanaget;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_recordNumber;
    private javax.swing.JTextField tf_tuoi;
    // End of variables declaration//GEN-END:variables
}
