/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testassignment;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Array;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class StudentManager extends javax.swing.JFrame {

    ArrayList<Student> listStudent;
    DefaultTableModel model;
    final String path = "student.txt";
    int index;

    /**
     * Creates new form StudentManager
     */
    public StudentManager() {
        initComponents();
        setLocationRelativeTo(null);
        listStudent = new ArrayList<>();
        model = new DefaultTableModel();
        model = (DefaultTableModel) tb_student.getModel();
        index = 0;

    }

    public void addStudent() {
        Student student = new Student();
        student.setName(tf_nane.getText());
        student.setNganhhoc(cbb_nganhhoc.getSelectedItem().toString());
        student.setNgaysinh(tf_ngaysinh.getText());
        student.setDiem(tf_diem.getText());
        listStudent.add(student);
        writeFile(path, listStudent);
    }

    public void writeFile(String path, ArrayList<Student> list) {
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path));
            oos.writeObject(list);
            oos.close();
        } catch (Exception e) {
        }
    }

    public void filltoTable() {
        model.setRowCount(0);
        ArrayList<Student> list = readFile(path);
        for (Student s : list) {
            model.addRow(new Object[]{s.getName(), s.getNganhhoc(), s.getDiem(), s.getNgaysinh()});
        }
    }

    public boolean checkEmptyString() {
        if (tf_nane.getText().length() == 0 || tf_diem.getText().length() == 0 || tf_ngaysinh.getText().length() == 0) {
            return false;
        }
        return true;
    }

    public void showDetail() {

    }

    public boolean checkDate(String ngaysinh) {
        try {
            String date = "dd/MM/yyyy";
            SimpleDateFormat format = new SimpleDateFormat(date);
            format.parse(ngaysinh);
        } catch (Exception e) {

            return false;
        }

        return true;
    }

    public boolean checkPoint() {
        if (Double.parseDouble(tf_diem.getText()) < 0 || Double.parseDouble(tf_diem.getText()) > 10) {
            return false;
        }
        return true;
    }

    public ArrayList<Student> readFile(String path) {
        ArrayList<Student> list = new ArrayList<>();
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(path));
            list = (ArrayList<Student>) ois.readObject();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        return list;
    }

    public void delete() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nane = new javax.swing.JTextField();
        tf_ngaysinh = new javax.swing.JTextField();
        tf_diem = new javax.swing.JTextField();
        cbb_nganhhoc = new javax.swing.JComboBox();
        btn_mofile = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_student = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ho va ten");

        jLabel2.setText("Nganh hoc");

        jLabel3.setText("Diem");

        jLabel4.setText("Ngay sinh");

        cbb_nganhhoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CNTT", "Quan tri kinh doanh", "Quan tri mang", "Ngan hang", " " }));

        btn_mofile.setText("Mo file");
        btn_mofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mofileActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xoa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        tb_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ho va ten", "Nganh hoc", "Diem", "Ngay sinh"
            }
        ));
        tb_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_studentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_student);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_nane)
                    .addComponent(tf_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(tf_diem, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(cbb_nganhhoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_mofile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ghi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mofile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbb_nganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ghi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa))))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        if (checkEmptyString()) {
            try {
                if (!checkPoint()) {
                    JOptionPane.showMessageDialog(this, "Diem phai tu 0 den 10");
                    return;
                } else if (!checkDate(tf_ngaysinh.getText())) {
                    JOptionPane.showMessageDialog(this, "Ban phai nhap dung dinh dan ngay sinh");
                    return;
                } else {
                    addStudent();
                    filltoTable();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Diem nhap vao phai la so");
            }
        } else {
            JOptionPane.showMessageDialog(this, "khong de trong cac o nhap");
        }
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_mofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mofileActionPerformed
        // TODO add your handling code here:
        filltoTable();
    }//GEN-LAST:event_btn_mofileActionPerformed

    private void tb_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_studentMouseClicked
        // TODO add your handling code here:
        index = tb_student.getSelectedRow();
        Student student = listStudent.get(index);
        tf_diem.setText(student.getDiem());
        tf_nane.setText(student.getName());
        tf_ngaysinh.setText(student.getNgaysinh());
        cbb_nganhhoc.setSelectedIndex(index);   

    }//GEN-LAST:event_tb_studentMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        try {
            listStudent = readFile(path);
            index = tb_student.getSelectedRow();
            listStudent.remove(index);
            writeFile(path, listStudent);
            filltoTable();
        } catch (Exception e) {

        }


    }//GEN-LAST:event_btn_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new StudentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_mofile;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox cbb_nganhhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_student;
    private javax.swing.JTextField tf_diem;
    private javax.swing.JTextField tf_nane;
    private javax.swing.JTextField tf_ngaysinh;
    // End of variables declaration//GEN-END:variables
}
