/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql.hocsinh;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author HP
 */

public class QlSv extends javax.swing.JFrame {
       DefaultTableModel model ;
    ArrayList<Student> listSv ;
    Student sv;
    int index;
    /**
     * Creates new form QL_Nv
     */
    public QlSv() {
        initComponents();
        setLocationRelativeTo(null);
        listSv= new ArrayList<>();
        
       
    }
    public void checkvalidate(){
        
    }
    
    public void addStudent(){
         sv = new Student();
         sv.setName(tfName.getText());
         sv.setMark(Double.parseDouble(tfMark.getText()));
         sv.setMajor(cbb_Nganh.getSelectedItem().toString());
         listSv.add(sv);
         tf_hl.setText(sv.getGrade());
         cb_phanthuong.setSelected(sv.isBonus());
         
         
       
    }
     
    public void removeStudent(){
          index = table_ql.getSelectedRow();
        listSv.remove(index);
        
    }
    public void updateStudent(){
        index = table_ql.getSelectedRow();
        if(index>=0){
        sv = new Student();
        sv.setName(tfName.getText());
        sv.setMark(Double.parseDouble(tfMark.getText()));
        sv.setMajor(cbb_Nganh.getSelectedItem().toString());
        cb_phanthuong.setSelected(sv.isBonus());
        listSv.set(index, sv);
        
        }else{
            JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng muoonss");
        }
    }
    public void fillToTable(){
     model = (DefaultTableModel) table_ql.getModel();
        model.setRowCount(0);
        for(Student s:listSv){
            model.addRow(new Object[]{s.getName(),s.getMark(),s.getMajor(),s.getGrade(),s.isBonus()});
        }
    }
    public void showDetail(){
        index = table_ql.getSelectedRow();
        sv = listSv.get(index);
        tfName.setText(sv.getName());
        tfMark.setText(String.valueOf(sv.getMark()));
        tf_hl.setText(sv.getGrade());
        cb_phanthuong.setSelected(sv.isBonus());
        
        
        
    }
    public void orderByName(){
        Comparator<Student> com = (Student o1, Student o2) -> o1.getName().compareTo(o2.getName());
        Collections.sort(listSv,com);
                }
    public void orderByMark(){
        Comparator<Student> com = (Student o1, Student o2) -> {
            Double d1 = o1.getMark();
            Double d2 = o1.getMark();
            return d1.compareTo(d2);
        };
        Collections.sort(listSv,com);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_ql = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfMark = new javax.swing.JTextField();
        tf_hl = new javax.swing.JTextField();
        cbb_Nganh = new javax.swing.JComboBox();
        cb_phanthuong = new javax.swing.JCheckBox();
        btn_delete = new javax.swing.JButton();
        btn_repeat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_ql.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51)));
        table_ql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ và tên", "Điểm ", "Ngành", "Học lực", "Thưởng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_qlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ql);

        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("Cập nhập");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý sinh viên");

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Điểm");

        jLabel4.setText("Ngành");

        jLabel5.setText("Học lực");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMarkActionPerformed(evt);
            }
        });

        tf_hl.setEditable(false);

        cbb_Nganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ứng dụng phần mềm", "Lập trình ứng dụng moblie", " " }));

        cb_phanthuong.setText("Có phần thưởng ?");

        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_repeat.setText("Nhập  mới");
        btn_repeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_repeatActionPerformed(evt);
            }
        });

        jButton1.setText("Sắp xếp theo tên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sắp xếp theo điểm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbb_Nganh, 0, 340, Short.MAX_VALUE)
                                .addComponent(tf_hl)
                                .addComponent(tfMark)
                                .addComponent(tfName))
                            .addComponent(cb_phanthuong)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_repeat))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbb_Nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_hl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_phanthuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_delete)
                    .addComponent(btn_update)
                    .addComponent(btn_repeat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
       
        this.addStudent();
        this.fillToTable();
        
            
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:'
       
       this.updateStudent();
       this.fillToTable();
       this.removeStudent();
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tfMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarkActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btn_repeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_repeatActionPerformed
        // TODO add your handling code here:
        tfName.setText("");
        tfMark.setText("");
        tf_hl.setText("");
        cb_phanthuong.setSelected(false);
        
    }//GEN-LAST:event_btn_repeatActionPerformed

    private void table_qlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_qlMouseClicked
        // TODO add your handling code here:
        
        sv = new Student();
      index  = table_ql.getSelectedRow();
      sv = listSv.get(index);
      tfName.setText(sv.getName());
      tfMark.setText(String.valueOf(sv.getMark()));
      if(sv.getMajor().equalsIgnoreCase("Ứng dụng phần mềm")){
          cbb_Nganh.setSelectedIndex(0);
      }else{
          cbb_Nganh.setSelectedIndex(1);
      }
      tf_hl.setText(sv.getGrade());
      cb_phanthuong.setSelected(sv.isBonus());
        
    }//GEN-LAST:event_table_qlMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        this.removeStudent();
        this.fillToTable();
      
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.orderByName();
         this.fillToTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.orderByMark();
        this.fillToTable();for(Student s:listSv){
            System.out.println(s);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QlSv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QlSv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QlSv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QlSv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QlSv().setVisible(true);
            }
        });;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_repeat;
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox cb_phanthuong;
    private javax.swing.JComboBox cbb_Nganh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_ql;
    private javax.swing.JTextField tfMark;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tf_hl;
    // End of variables declaration//GEN-END:variables
}
